from pathlib import Path

PROGRAM_NAME = "double_slit"

OUTPUT_IMAGE = "outputs/double_slit_detector_plane.png"

markdown = f"""
# {PROGRAM_NAME} — Generated Documentation

# Purpose

This document was automatically generated by the DPI documentation generator.

The goal of the program is to simulate:

field propagation
→ detector-plane interaction
→ observable intensity formation.

---

# Generated Outputs

Output artifact:

{OUTPUT_IMAGE}

This output contains:

- detector-plane intensity structure
- interference geometry
- coherence organization
- observable propagation behavior

---

# Python Explanation

The program used Python to:

- generate detector positions
- compute propagation distances
- simulate oscillatory propagated fields
- combine propagated contributions
- compute detector intensity
- render detector-plane visualizations

Libraries used:

- NumPy
- Matplotlib

---

# Math Explanation

The simulation used:

- geometric distance calculations
- complex exponentials
- oscillatory propagation
- interference summation
- detector intensity conversion

Core mathematical structure:

exp(i k r)

where:

- i = imaginary unit
- k = wave number
- r = propagation distance

---

# Physics Explanation

The simulation modeled:

1. propagation from two slits
2. phase accumulation
3. detector-plane interaction
4. observable intensity formation

Bright detector regions represented:

constructive interference.

Dark detector regions represented:

destructive interference.

---

# Observability Interpretation

The detector plane became:

a spatial observability surface.

Different detector positions encoded:

different propagation relationships.

The output demonstrated:

structured observable geometry emerging from propagation behavior.

---

# DPI Relevance

This output becomes:

the first persistent detector-plane observability artifact.

Future DPI stages may include:

- noise
- decoherence
- frame accumulation
- detector degradation
- coherence trajectories
- manifold projections
- runtime telemetry
"""

docs_path = Path("docs")
docs_path.mkdir(exist_ok=True)

output_file = docs_path / f"{PROGRAM_NAME}_generated.md"

output_file.write_text(markdown)

print(f"Generated documentation: {output_file}")
